---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-operator
spec:
  destination:
    name: osc-cl1
    namespace: kubeflow
  project: os-climate
  source:
    path: training-operator/overlays/osc/osc-cl1
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
