---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  namespace: okd-centos
  name: okd-golang-builder
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 2
  source:
    git:
      ref: main
      uri: https://github.com/okd-project/images
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: "centos:stream9"
        namespace: okd-centos
      dockerfilePath: okd-golang-builder.Dockerfile
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: centos:okd-golang-builder
      namespace: okd-centos
  triggers:
  - type: ConfigChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: "centos:stream9"
        namespace: okd-centos
    type: ImageChange
