apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: octo-otel-dev
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'otel-dev*'
      server: 'https://api.smaug.na.operate-first.cloud:6443'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:octo-otel-dev:project-admin, applications, get, octo-otel-dev/*, allow
        - p, proj:octo-otel-dev:project-admin, applications, create, octo-otel-dev/*, allow
        - p, proj:octo-otel-dev:project-admin, applications, update, octo-otel-dev/*, allow
        - p, proj:octo-otel-dev:project-admin, applications, delete, octo-otel-dev/*, allow
        - p, proj:octo-otel-dev:project-admin, applications, sync, octo-otel-dev/*, allow
        - p, proj:octo-otel-dev:project-admin, applications, override, octo-otel-dev/*, allow
        - p, proj:octo-otel-dev:project-admin, applications, action/*, octo-otel-dev/*, allow
      groups:
        - octo-otel-dev
        - operate-first
