apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kepler
  namespace: argocd
spec:
  project: os-climate
  source:
    path: kepler/overlays/osc/osc-cl2
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  destination:
    name: osc-cl2
    namespace: kepler-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
