---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfp-tekton
spec:
  destination:
    name: osc-cl2
    namespace: kubeflow
  project: operate-first
  source:
    path: kfp-tekton/overlays/osc/osc-cl2
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
