---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendatahub-operator
spec:
  destination:
    name: osc-cl2
    namespace: opendatahub-operator
  project: os-climate
  source:
    path: odh-operator/overlays/osc/osc-cl2
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
